FAIRiCUBE/data-requests

- stac_dist/eu_demography/eu_demography.json
{"filename": "eu_demography/eu_demography.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/eu_demography/eu_demography.json

- stac_dist/Vienna_vineyard_area/Vienna_vineyard_area.json
{"filename": "Vienna_vineyard_area/Vienna_vineyard_area.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/Vienna_vineyard_area/Vienna_vineyard_area.json

- stac_dist/Vienna_building_volume/Vienna_building_volume.json
{"filename": "Vienna_building_volume/Vienna_building_volume.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/Vienna_building_volume/Vienna_building_volume.json

- stac_dist/Vienna_districts/Vienna_districts.json
{"filename": "Vienna_districts/Vienna_districts.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/Vienna_districts/Vienna_districts.json

- stac_dist/ADC_Arable_Land_Markers_Autumn/ADC_Arable_Land_Markers_Autumn.json
{"filename": "ADC_Arable_Land_Markers_Autumn/ADC_Arable_Land_Markers_Autumn.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/ADC_Arable_Land_Markers_Autumn/ADC_Arable_Land_Markers_Autumn.json

- stac_dist/ADC_Arable_Land_Markers_Spring/ADC_Arable_Land_Markers_Spring.json
{"filename": "ADC_Arable_Land_Markers_Spring/ADC_Arable_Land_Markers_Spring.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/ADC_Arable_Land_Markers_Spring/ADC_Arable_Land_Markers_Spring.json

- stac_dist/ADC_arable_land_markers_no_ndvi/ADC_arable_land_markers_no_ndvi.json
{"filename": "ADC_arable_land_markers_no_ndvi/ADC_arable_land_markers_no_ndvi.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/ADC_arable_land_markers_no_ndvi/ADC_arable_land_markers_no_ndvi.json

- stac_dist/ADC_Crop_Parcels_Crop_Code/ADC_Crop_Parcels_Crop_Code.json
{"filename": "ADC_Crop_Parcels_Crop_Code/ADC_Crop_Parcels_Crop_Code.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/ADC_Crop_Parcels_Crop_Code/ADC_Crop_Parcels_Crop_Code.json

- stac_dist/ADC_Grassland_Markers_NDVI_Spring/ADC_Grassland_Markers_NDVI_Spring.json
{"filename": "ADC_Grassland_Markers_NDVI_Spring/ADC_Grassland_Markers_NDVI_Spring.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/ADC_Grassland_Markers_NDVI_Spring/ADC_Grassland_Markers_NDVI_Spring.json

- stac_dist/ADC_Grassland_Markers_No_Mowing/ADC_Grassland_Markers_No_Mowing.json
{"filename": "ADC_Grassland_Markers_No_Mowing/ADC_Grassland_Markers_No_Mowing.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/ADC_Grassland_Markers_No_Mowing/ADC_Grassland_Markers_No_Mowing.json

- stac_dist/ADC_Crop_Rotation_Index/ADC_Crop_Rotation_Index.json
{"filename": "ADC_Crop_Rotation_Index/ADC_Crop_Rotation_Index.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/ADC_Crop_Rotation_Index/ADC_Crop_Rotation_Index.json

- stac_dist/ADC_Crop_Parcels_Field_ID/ADC_Crop_Parcels_Field_ID.json
{"filename": "ADC_Crop_Parcels_Field_ID/ADC_Crop_Parcels_Field_ID.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/ADC_Crop_Parcels_Field_ID/ADC_Crop_Parcels_Field_ID.json

- stac_dist/Precipitation_Netherlands/Precipitation_Netherlands.json
{"filename": "Precipitation_Netherlands/Precipitation_Netherlands.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/Precipitation_Netherlands/Precipitation_Netherlands.json

- stac_dist/LGN_Monitoring/LGN_Monitoring.json
{"filename": "LGN_Monitoring/LGN_Monitoring.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/LGN_Monitoring/LGN_Monitoring.json

- stac_dist/Temperature_Netherlands/Temperature_Netherlands.json
{"filename": "Temperature_Netherlands/Temperature_Netherlands.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/Temperature_Netherlands/Temperature_Netherlands.json

- stac_dist/Vienna_imperviousness_density_2018/Vienna_imperviousness_density_2018.json
{"filename": "Vienna_imperviousness_density_2018/Vienna_imperviousness_density_2018.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/Vienna_imperviousness_density_2018/Vienna_imperviousness_density_2018.json

- stac_dist/water_and_wetness_20m/water_and_wetness_20m.json
{"filename": "water_and_wetness_20m/water_and_wetness_20m.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/water_and_wetness_20m/water_and_wetness_20m.json

- stac_dist/tree_cover_density_10m/tree_cover_density_10m.json
{"filename": "tree_cover_density_10m/tree_cover_density_10m.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/tree_cover_density_10m/tree_cover_density_10m.json

- stac_dist/tree_cover_density_20m/tree_cover_density_20m.json
{"filename": "tree_cover_density_20m/tree_cover_density_20m.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/tree_cover_density_20m/tree_cover_density_20m.json

- stac_dist/imperviousness_10m/imperviousness_10m.json
{"filename": "imperviousness_10m/imperviousness_10m.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/imperviousness_10m/imperviousness_10m.json

- stac_dist/imperviousness_20m/imperviousness_20m.json
{"filename": "imperviousness_20m/imperviousness_20m.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/imperviousness_20m/imperviousness_20m.json

- stac_dist/small_woody_features_2018/small_woody_features_2018.json
{"filename": "small_woody_features_2018/small_woody_features_2018.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/small_woody_features_2018/small_woody_features_2018.json

- stac_dist/small_woody_features_2015/small_woody_features_2015.json
{"filename": "small_woody_features_2015/small_woody_features_2015.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/small_woody_features_2015/small_woody_features_2015.json

- stac_dist/grassland_10m/grassland_10m.json
{"filename": "grassland_10m/grassland_10m.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/grassland_10m/grassland_10m.json

- stac_dist/grassland_20m/grassland_20m.json
{"filename": "grassland_20m/grassland_20m.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/grassland_20m/grassland_20m.json

- stac_dist/forest_type_10m/forest_type_10m.json
{"filename": "forest_type_10m/forest_type_10m.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/forest_type_10m/forest_type_10m.json

- stac_dist/forest_type_20m/forest_type_20m.json
{"filename": "forest_type_20m/forest_type_20m.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/forest_type_20m/forest_type_20m.json

- stac_dist/european_settlement_map_2018/european_settlement_map_2018.json
{"filename": "european_settlement_map_2018/european_settlement_map_2018.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/european_settlement_map_2018/european_settlement_map_2018.json

- stac_dist/european_settlement_map_2015/european_settlement_map_2015.json
{"filename": "european_settlement_map_2015/european_settlement_map_2015.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/european_settlement_map_2015/european_settlement_map_2015.json

- stac_dist/global_pesticide_grids_crops/global_pesticide_grids_crops.json
{"filename": "global_pesticide_grids_crops/global_pesticide_grids_crops.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/global_pesticide_grids_crops/global_pesticide_grids_crops.json

- stac_dist/global_pesticide_grids_qi/global_pesticide_grids_qi.json
{"filename": "global_pesticide_grids_qi/global_pesticide_grids_qi.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/global_pesticide_grids_qi/global_pesticide_grids_qi.json

- stac_dist/dominant_leaf_type_20m/dominant_leaf_type_20m.json
{"filename": "dominant_leaf_type_20m/dominant_leaf_type_20m.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/dominant_leaf_type_20m/dominant_leaf_type_20m.json

- stac_dist/soil_ph_city_of_luxembourg/soil_ph_city_of_luxembourg.json
{"filename": "soil_ph_city_of_luxembourg/soil_ph_city_of_luxembourg.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/soil_ph_city_of_luxembourg/soil_ph_city_of_luxembourg.json

- stac_dist/air_temperature_city_of_luxembourg_2017/air_temperature_city_of_luxembourg_2017.json
{"filename": "air_temperature_city_of_luxembourg_2017/air_temperature_city_of_luxembourg_2017.json", "item_type": "stac_dist", "change_type": "Update", "user": "FAiRICUBE", "data_owner": true}
> ChangeType.update stac_dist/air_temperature_city_of_luxembourg_2017/air_temperature_city_of_luxembourg_2017.json
